Repository BC-MAY-21-ROR/kata-07-reloj-checador-team-01, pull requests merged in 2021-09, with the labels that each got.

#6 Creates mockups and add pull request template
  PULL_REQUEST_TEMPLATE.md
  mockups/desktop/DEKSTOP-ACTION-DESICION.png
  mockups/desktop/DEKSTOP-CREATE-EMPLOYEES.png
  mockups/desktop/DEKSTOP-CREATE-STORES.png
  mockups/desktop/DEKSTOP-HOME-CHECK-IN.png
  mockups/desktop/DEKSTOP-HOME-CHECK-OUT.png
  mockups/desktop/DEKSTOP-HOME-LOGO.png
  mockups/desktop/DEKSTOP-HOME.png
  mockups/desktop/DEKSTOP-LIST-EMPLOYEES.png
  mockups/desktop/DEKSTOP-LIST-STORES.png
  mockups/desktop/DEKSTOP-REGISTER.png
  mockups/desktop/DEKSTOP-REPORT-ABSENCE.png
  mockups/desktop/DEKSTOP-REPORT-ATTENDANCE.png
  mockups/desktop/DEKSTOP-REPORT-AVARENGE.png
  mockups/mobile/MOBILE ABSENCE LIST.png
  mockups/mobile/MOBILE CREATE-STORES.png
  mockups/mobile/MOBILE EMPLOYES LIST.png
  mockups/mobile/MOBILE REGISTER-EMPLOYES.png
  mockups/mobile/MOBILE REPORT ATTENDANCE.png
  mockups/mobile/MOBILE REPORT AVARANGE.png
  mockups/mobile/MOBILE STORES LIST.png
  mockups/mobile/MOBILE-ACTION-DESICION.png
  mockups/mobile/MOBILE-HOME-CHECK-IN.png
  mockups/mobile/MOBILE-HOME-CHECK-OUT.png
  mockups/mobile/MOBILE-HOME-ERROR.png
  mockups/mobile/MOBILE-HOME-LOGO.png
  mockups/mobile/MOBILE-REGISTER.png
Labels: ready for review

#7 Add react to project
  .env.example
  Gemfile
  Gemfile.lock
  app/controllers/static_controller.rb
  app/controllers/v1/things_controller.rb
  app/javascript/components/App.js
  app/javascript/packs/application.js
  app/javascript/packs/server_rendering.js
  app/views/layouts/application.html.erb
  app/views/static/index.html.erb
  babel.config.js
  config/routes.rb
  config/webpacker.yml
  package-lock.json
  package.json
  yarn.lock
Labels: mentor review required, ready for review

#11 Add sass to rails project with webpacker
  Gemfile
  Gemfile.lock
  app/javascript/packs/application.js
  app/javascript/packs/applications.scss
  app/views/layouts/application.html.erb
  bin/yarn
  config/initializers/assets.rb
  config/webpack/base.js
  config/webpack/development.js
  config/webpack/production.js
  config/webpack/test.js
  config/webpacker.yml
  package.json
  postcss.config.js
  yarn.lock
Labels: mentor review required, ready for review, review required

#17 Add rubocop
  .rubocop.yml
  Gemfile
  Gemfile.lock
Labels: mentor review required, ready for review, review required

#19 Add Testing Library rspec
  .rspec
  .ruby-version
  Gemfile
  Gemfile.lock
  config/initializers/generators.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  test/application_system_test_case.rb
  test/channels/application_cable/connection_test.rb
  test/controllers/.keep
  test/fixtures/files/.keep
  test/helpers/.keep
  test/integration/.keep
  test/mailers/.keep
  test/models/.keep
  test/system/.keep
  test/test_helper.rb
Labels: mentor review required, ready for review, review required
