Repository BC-MAY-21-ROR/kata-07-reloj-checador-team-01, pull requests merged in 2021-10, with the labels that each got.

#20 Add rubycritic and babel plugin
  Gemfile
  Gemfile.lock
  package.json
  yarn.lock
Labels: mentor review required, ready for review, review required

#21 Set Heroku Deployment Configuration
  app/javascript/packs/applications.scss
  app/views/layouts/application.html.erb
  app/views/layouts/partials/_footer.html.erb
  app/views/layouts/partials/_header.html.erb
  app/views/static/index.html.erb
  package.json
  postcss.config.js
  tailwind.config.js
  yarn.lock
Labels: mentor review required, ready for review, review required

#22 creation of the ReadMe.md file
  README.md
Labels: mentor review required, ready for review, review required

#25 Add Devise gem for user authentication
  .env.example
  Gemfile
  Gemfile.lock
  app/javascript/packs/application.js
  app/javascript/packs/applications.scss
  app/models/user.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/partials/_header.html.erb
  config/environments/development.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20211004220835_devise_create_users.rb
  db/schema.rb
  spec/models/user_spec.rb
Labels: ready for review

#31 Add user role field to users table
  app/models/user.rb
  app/views/devise/shared/_links.html.erb
  config/routes.rb
  db/migrate/20211004220835_devise_create_users.rb
  db/migrate/20211006003056_add_role_to_users.rb
  db/schema.rb
  spec/models/user_spec.rb
Labels: mentor review required, ready for review, review required

#33 cancan configuration.
  Gemfile
  Gemfile.lock
  app/models/ability.rb
Labels: mentor review required, ready for review, review required

#37 Add styles in admin login view
  app/javascript/packs/applications.scss
  app/views/application/_basic_layout.html.erb
  app/views/application/_full_layout.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/layouts/application.html.erb
  app/views/static/index.html.erb
  tailwind.config.js
Labels: mentor review required, ready for review, review required

#35 Add scaffolding for Company
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/companies_controller.rb
  app/models/company.rb
  app/views/companies/_company.json.jbuilder
  app/views/companies/_form.html.erb
  app/views/companies/edit.html.erb
  app/views/companies/index.html.erb
  app/views/companies/index.json.jbuilder
  app/views/companies/new.html.erb
  app/views/companies/show.html.erb
  app/views/companies/show.json.jbuilder
  config/routes.rb
  db/migrate/20211012205447_create_companies.rb
  db/migrate/20211012205601_add_deleted_at_to_companies.rb
  db/schema.rb
  db/seeds.rb
  spec/models/company_spec.rb
  spec/requests/companies_spec.rb
  spec/routing/companies_routing_spec.rb
  spec/views/companies/edit.html.erb_spec.rb
  spec/views/companies/index.html.erb_spec.rb
  spec/views/companies/new.html.erb_spec.rb
  spec/views/companies/show.html.erb_spec.rb
Labels: mentor review required, ready for review, review required

#42 Restructure the check form.
  app/javascript/components/App.js
  app/javascript/components/CheckIn.jsx
  app/javascript/components/CheckIn/CheckIn.jsx
  app/javascript/components/CheckIn/CheckInSchema.js
Labels: mentor review required, ready for review, review required

#44 add react-toastify.
  app/javascript/components/App.js
  app/javascript/components/Toastify.js
  app/javascript/components/ToastifyConfiguration.js
  app/views/layouts/partials/_alerts.html.erb
  package.json
  yarn.lock
Labels: mentor review required, ready for review, review required

#51 Creates attendance scaffold
  app/controllers/attendances_controller.rb
  app/helpers/attendances_helper.rb
  app/models/attendance.rb
  app/models/employee.rb
  app/views/attendances/_attendance.json.jbuilder
  app/views/attendances/_form.html.erb
  app/views/attendances/edit.html.erb
  app/views/attendances/index.html.erb
  app/views/attendances/index.json.jbuilder
  app/views/attendances/new.html.erb
  app/views/attendances/show.html.erb
  app/views/attendances/show.json.jbuilder
  config/application.rb
  config/routes.rb
  db/migrate/20211015005215_create_attendances.rb
  db/schema.rb
  spec/models/attendance_spec.rb
  spec/requests/attendances_spec.rb
  spec/views/attendances/edit.html.erb_spec.rb
  spec/views/attendances/index.html.erb_spec.rb
  spec/views/attendances/new.html.erb_spec.rb
  spec/views/attendances/show.html.erb_spec.rb
Labels: mentor review required, ready for review, review required

#49 Add employees scaffold styles
  app/javascript/packs/application.js
  app/javascript/packs/components/_button.scss
  app/javascript/packs/components/_field.scss
  app/javascript/packs/components/_table.scss
  app/views/application/_crud_layout.html.erb
  app/views/employees/_form.html.erb
  app/views/employees/edit.html.erb
  app/views/employees/index.html.erb
  app/views/employees/new.html.erb
  app/views/employees/show.html.erb
  tailwind.config.js
Labels: mentor review required, ready for review, review required

#56 Add axios
  package.json
  yarn.lock
Labels: mentor review required, ready for review, review required

#66 Add registration of Check in employees attendance functionality
  app/controllers/attendances_controller.rb
  app/controllers/employees_controller.rb
  app/javascript/components/CheckIn/CheckIn.jsx
  app/models/attendance.rb
  app/models/employee.rb
  config/routes.rb
  spec/models/attendance_spec.rb
Labels: mentor review required, ready for review, review required

#68 Remove field id_user in attendances scaffolding
  Gemfile
  Gemfile.lock
  app/controllers/attendances_controller.rb
  app/helpers/attendances_helper.rb
  app/helpers/employees_helper.rb
  app/models/attendance.rb
  app/models/employee.rb
  app/views/attendances/_attendance.json.jbuilder
  app/views/attendances/_form.html.erb
  app/views/attendances/index.html.erb
  app/views/attendances/show.html.erb
  db/migrate/20211015005215_create_attendances.rb
  db/migrate/20211025233428_remove_user_id_from_attendances.rb
  db/schema.rb
  spec/controllers/attendance_controller_spec.rb
  spec/factories/attendances.rb
  spec/factories/companies.rb
  spec/factories/employees.rb
  spec/factories/users.rb
  spec/models/attendance_spec.rb
  spec/models/employee_spec.rb
  spec/rails_helper.rb
  spec/support/factory_bot.rb
Labels: ready for review, review required

#69 Add Check Out Functionality
  app/javascript/components/CheckIn/CheckIn.jsx
  app/javascript/components/CheckIn/CheckInSchema.js
Labels: mentor review required, ready for review, review required

#70 Add report for attendances by day
  app/models/attendance.rb
  app/views/attendances/today.html.erb
  app/views/dashboard/admin.html.erb
  config/routes.rb
  db/migrate/20211025233428_remove_user_id_from_attendances.rb
Labels: mentor review required, ready for review, review required
