Repository BC-MAY-21-ROR/kata-07-reloj-checador-team-01, pull requests merged in 2021-11, with the labels that each got.

#71 Add Average time by month report
  app/controllers/attendances_controller.rb
  app/controllers/employees_controller.rb
  app/javascript/components/CheckIn/CheckIn.jsx
  app/models/attendance.rb
  app/models/employee.rb
  app/views/dashboard/admin.html.erb
  app/views/employees/avg_time.html.erb
  config/routes.rb
  spec/factories/attendances.rb
  spec/factories/employees.rb
  spec/models/employee_spec.rb
Labels: mentor review required, ready for review, review required

#74 Add file to remove user_id from heroku databases
  db/migrate/20211025233428_remove_user_id_from_attendances.rb
Labels: ready for review

#72 Add absences by month report
  app/helpers/application_helper.rb
  app/models/attendance.rb
  app/models/employee.rb
  app/views/dashboard/admin.html.erb
  app/views/employees/absences.html.erb
  config/routes.rb
  spec/factories/employees.rb
  spec/models/employee_spec.rb
Labels: mentor review required, ready for review
